### ISSUE TITLE
Download pre-trained model, permission denied 

### ISSUE THREAD

**Issue by serenayj** [JonghwanMun/LGI4temporalgrounding#3]
Hi, I tried to download the pre-train model from download_pretrained_models.sh, but the error came up and showed: 
`--2020-06-22 15:19:19--  http://cvlab.postech.ac.kr/~jonghwan/data/LGI/LGI_pretrained_models.tar.gz
Resolving cvlab.postech.ac.kr (cvlab.postech.ac.kr)... 141.223.85.126
Connecting to cvlab.postech.ac.kr (cvlab.postech.ac.kr)|141.223.85.126|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 321923441 (307M) [application/x-gzip]
LGI_pretrained_models.tar.gz: Permission denied
`

Could you tell me what could possibly go wrong? Thanks.

**Comment by JonghwanMun** [comment]
For me, when I directly download the files using chrome, the link "http://cvlab.postech.ac.kr/~jonghwan/data/LGI/LGI_pretrained_models.tar.gz" works and is available.
Can you directly download the files using chrome instead of the terminal?

I will check the reason why **wget** is not working.
Thanks.

**Comment by serenayj** [comment]
Actually, this error occured at my end; I used sudo wget and the problem went away. Thank you for your response.
